-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS Henkilo CASCADE;
DROP TABLE IF EXISTS Ajoneuvo CASCADE;
DROP TABLE IF EXISTS Alue CASCADE;
DROP TABLE IF EXISTS Vartija CASCADE;
DROP TABLE IF EXISTS Aluelupa CASCADE;
DROP TABLE IF EXISTS Vartiointi CASCADE;
DROP TABLE IF EXISTS Aluelupaauto CASCADE;


